### ISSUE TITLE
Backspace support for length limited input

### ISSUE THREAD

**Issue by HongJunChea** [HongJunChea/payroll-system#4]
use backspace maybe will change the total character

for employee ID such as E0001, have 5 character. When i enter ID in menu number 6, basically we enter  'E0001' is working, But when i 'E00' and use backspace, it will become 'E0' and i want to enter '001', it will stop when i enter untill '00' and it will show employee not found

**Comment by Poleric** [comment]
added with input_text procedure in da313e98fc49eb87f11976878d2953401f5a51cb
